### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by dweidner** [theKashey/dom-focus-lock#2]
I have problems using this module within my project. I am using webpack and babel and get the following error when I try to import your module:

```
ERROR in ../node_modules/dom-focus-lock/dist/index.js
Module not found: Error: Can't resolve 'focusLock' in '/usr/src/app/node_modules/dom-focus-lock/dist'
 @ ../node_modules/dom-focus-lock/dist/index.js 80:4-82:6
 @ ./js/components/MenuButton.js
 @ ./js/main.js
 @ multi ./js/main.js
```

It seems as if webpack cannot resolve your focus-lock dependency. Do you have an idea, what is going wrong?

I am using node v10.12, npm v6.4.1 and webpack 4.27.1

**Comment by theKashey** [comment]
🤷‍♂️ `focus-lock` is not `focusLock` 🤷‍♂️

**Comment by theKashey** [comment]
In short - the main goal was `umd` package, but some code to make it work was causing issues for plain webpack-oriented dist.

Not it works everywhere -> just update to 1.0.3

**Comment by dweidner** [comment]
Thank you for the quick response 👍
