### ISSUE TITLE
Modal with just <details> elements skip trap 

### ISSUE THREAD

**Issue by hejuhenryk** [theKashey/dom-focus-lock#9]
```
<div id="elemene-with-lock" >
        <details>
            <summary>text</summary>
                text
        </details>
        <details>
            <summary>text</summary>
                text
        </details>
        <details>
            <summary>text</summary>
                text
        </details>
</div>
```
i added tabindex to first summary to make it work -> https://codesandbox.io/s/bold-estrela-9iejzf?file=/index.html

**Comment by theKashey** [comment]
👍 `details` are tabbable elements, but are not listed as such - https://github.com/theKashey/focus-lock/blob/master/src/utils/tabbables.ts#L4

**Comment by theKashey** [comment]
It seems to be more codesandbox issue as `focus-lock` version got "locked" at the very old version and not being update for some reason
<img width="231" alt="image" src="https://user-images.githubusercontent.com/582410/201505913-5596b829-d42f-4193-b246-7aed5ed38a56.png">

I've released a new version of `dom-focus-lock` with transitive dependency updated. Please try `1.1.0`
Here is your case working - https://codesandbox.io/s/tender-ritchie-zbbf9z?file=/src/index.js
